### ISSUE TITLE
MessageMut using owned String and Descendants

### ISSUE THREAD

**Issue by sempervictus** [wokket/rust-hl7#20]
The original implementation using String references is exceptionally good at read-oriented processing - data isn't copied, all segments and sub-segments are accessible, and we have good API to do so.
However, since we carry a reference, a lot of Rust's idiomatic standards dont play nice - `FromStr` is not a thing here.
What do you think about a follow-up MessageMut and descendants for owned String with all those conveniences. The string ref bit is super useful for large quantities of messages being read and parsed out, so i think we want to keep it working that way. However, if we mirror a mutable implementation, it should give less discerning consumers a very standard API, mutability of messages (nice for an HL7 gen - my internal one is gross: string subs and message::from), and fit the standard trait paradigms from the ecosystem.
Thoughts?

**Comment by wokket** [comment]
When I started to look into it I realised `FromStr` assumes parsing will always succeed and so only returns `T`, not `Result<T,_>` which is why I implemented TryFrom instead.

Is there any other reason you'd like a `FromStr` impl otherwise I vote to ignore this and just use the `TryFrom` code already in  place.

**Comment by wokket** [comment]
Resolved by #19
